export const NICHE_OPTIONS: { value: string; label: string }[] = [
  { value: "fitness", label: "Fitness" },
  { value: "health", label: "Health" },
  { value: "dating", label: "Dating" },
  { value: "finance", label: "Finance" },
  { value: "crypto", label: "Crypto" },
  { value: "investing", label: "Investing" },
  { value: "ai", label: "AI" },
  { value: "startups", label: "Startups" },
  { value: "productivity", label: "Productivity" },
  { value: "nutrition", label: "Nutrition" },
  { value: "mental health", label: "Mental Health" },
  { value: "tech", label: "Tech" },
  { value: "cooking", label: "Cooking" },
  { value: "gaming", label: "Gaming" },
  { value: "fashion", label: "Fashion" },
  { value: "music", label: "Music" },
  { value: "travel", label: "Travel" },
  { value: "beauty", label: "Beauty" },
  { value: "entrepreneurship", label: "Business" },
  { value: "photography", label: "Photography" },
  { value: "parenting", label: "Parenting" },
  { value: "pets", label: "Pets" },
  { value: "education", label: "Education" },
  { value: "language learning", label: "Language Learning" },
  { value: "sports", label: "Sports" },
  { value: "diy", label: "DIY" },
  { value: "motivation", label: "Motivation" },
  { value: "self improvement", label: "Self Improvement" },
  { value: "career", label: "Career" },
  { value: "custom", label: "Custom…" },
];
