export const NICHE_OPTIONS: { value: string; label: string }[] = [
  { value: "__group_lifestyle", label: "--- Lifestyle ---" },
  { value: "fashion", label: "Fashion" },
  { value: "food & cooking", label: "Food & Cooking" },
  { value: "parenting", label: "Parenting" },
  { value: "relationships", label: "Relationships" },
  { value: "travel", label: "Travel" },
  { value: "__group_business", label: "--- Business & Money ---" },
  { value: "business & entrepreneurship", label: "Business & Entrepreneurship" },
  { value: "crypto", label: "Crypto" },
  { value: "finance & investing", label: "Finance & Investing" },
  { value: "real estate", label: "Real Estate" },
  { value: "__group_creator", label: "--- Creator & Entertainment ---" },
  { value: "breaking news", label: "Breaking News" },
  { value: "pop culture", label: "Pop Culture" },
  { value: "entertainment", label: "Entertainment" },
  { value: "celebrity", label: "Celebrity" },
  { value: "beauty & makeup", label: "Beauty & Makeup" },
  { value: "comedy", label: "Comedy" },
  { value: "diy & crafts", label: "DIY & Crafts" },
  { value: "gaming", label: "Gaming" },
  { value: "music", label: "Music" },
  { value: "__group_health", label: "--- Health & Wellness ---" },
  { value: "fitness", label: "Fitness" },
  { value: "mental health", label: "Mental Health" },
  { value: "motivation", label: "Motivation" },
  { value: "__group_other", label: "--- Other ---" },
  { value: "pets", label: "Pets" },
  { value: "sports", label: "Sports" },
  { value: "tech & ai", label: "Tech & AI" },
  { value: "custom", label: "Custom…" },
];
